.TH wmsysmon 1 "2001-04-09" Debian "System Monitor Dockable Application" 

.SH NAME
wmsysmon \- Windowmaker dock-app for monitoring your system.

.SH SYNOPSIS
Windowmaker dock-app for monitoring your system.

.SH DESCRIPTION
wmsysmon is a dockable application for Windowmaker (and possibly Afterstep). It monitors Memory, Swap, Disk IO, uptime and
interrupts. 

.SH ENVIRONMENT
Requires:
.RS
.I libc6 (>= 2.2.2-2) 
       GNU C Library: Shared libraries and Timezone data 

.I xlibs (>= 4.0.1-11) 
       X Window System client libraries 
.RE

.SH AUTHOR
Norbert Tretkowski is responsible for this Debian package. 
.SH "SEE ALSO"
